version: '3.8'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/parser/
      - static_value:/parser/static_backend/
    ports:
      - 1337:8000
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    build: ./project
    command: celery -A web worker -l info
    volumes:
      - ./project/:/parser/
      - static_value:/parser/static_backend/
    env_file:
      - ./.env
    depends_on:
      - redis
      - web

  celery-beat:
    build: ./project
    command: celery -A web beat -l info
    volumes:
      - ./project/:/parser/
    env_file:
      - ./.env
    depends_on:
      - redis
      - web

volumes:
  static_value: