# Generated by Django 4.2.5 on 2023-09-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_create'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
